export const lightTheme = {
    textColor: "#484848",
    iconColor: "#118086",
    subTextColor: "#767676",
    headerActionColor: "#ffffff",
    accentColor: "#118086",
    secondaryAccentColor: "#118086",
    priorityHigh: "#FF0000",
    priorityMid: "orange",
    priorityLow: "#1E90FF",
    background: "#FAFAFA",
    deleteColor: "#E53935",
    cardBackground: "#fff",
    bottomsheetColor: "#FFFFFF",
    taskCardColor: "#118086",
    fabGroup: "white",
};

export const darkTheme = {
    textColor: "#ffffff",
    subTextColor: "rgba(255,255,255,0.7)",
    iconColor: "#ffffff",
    headerActionColor: "#ffffff",
    accentColor: "#212121",
    secondaryAccentColor: "#3399ff",
    priorityHigh: "red",
    priorityMid: "orange",
    priorityLow: "dodgerblue",
    background: "#1C1C1D",
    cardBackground: "#212121",
    bottomsheetColor: "#212121",
    taskCardColor: "white",
    fabGroup: "#3399ff",
};
